### PR TITLE
Implementation of solutions 

### PR DESCRIPTION
**Pull request by unrealwork**
@SEMrushQA 
Finally, I have finished all tasks solution. Again, I apologize for the bunch of unnecessary PRs.

---

Every task has a personal README.md file where you can find a brief description of a solution.
If you have any question, I will answer it with pleasure.

---

I will look forward to your сheck.

### CODE REVIEW

**Comment by unrealwork** [comment]
@SEMrushQA Is it will be checked or should I do anything else?

**Comment by SEMrushQA** [comment]
@unrealwork It will be checked as soon as possible, sorry for the delay.

**Comment by unrealwork** [comment]
@SEMrushTasks 
Hi! Is the task yet actual?

**Comment by SEMrushTasks** [comment]
Did you respond to some vacancy? Which one?

**Comment by SEMrushTasks** [comment]
@unrealwork Did you interested to some vacancy? Which one?

**Pull request closed without merging**
